services:
  platformio:
    build:
      context: .
      dockerfile: pio.Dockerfile
    volumes:
      - .:/home/BC95NB:rw
    working_dir: /home/BC95NB
    command: 
      - /bin/sh
      - -c
      - |
        ./scripts/test.sh
        ./scripts/check.sh
    container_name: platformio
    tty: true